//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LynLogger.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LynLogger.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //以下代码将舰娘名字去掉“改二”和“改”之后，反转，并按反转后的名字排序
        ///
        /////引入必要的命名空间
        ///using LynLogger;         //插件主命名空间
        ///using LynLogger.Models;  //插件数据模型命名空间
        ///using System;            //标准系统命名空间
        ///using System.Linq;       //Linq扩展方法空间
        ///
        /////标注处理排序用的类名称 CustomSorter.Sorter
        ///[assembly: ComparerClass(&quot;CustomSorter.Sorter&quot;)]
        ///
        /////定义命名空间CustomSorter
        ///namespace CustomSorter {
        ///
        ///  //定义公开类Sorter 继承于LynLogger.CustomComparerBase&lt;LynLogger.Models.Ship&gt;
        ///  public class Sorter : CustomComparerBase&lt;Ship&gt; {
        ///
        ///    //重写父类的比较方法
        ///    public override int C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TemplateCustomShipSorter {
            get {
                return ResourceManager.GetString("TemplateCustomShipSorter", resourceCulture);
            }
        }
    }
}
